=== sivhg/Test/qlsv.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dssinhvien">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sinhvien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="masv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="sv[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tensv" type="xs:string"/>
                            <xs:element name="gioitinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Nam|Nu"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="malop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{4}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="diem" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sivhg/Test/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<dssinhvien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="qlsv.xsd">
    <sinhvien>
        <masv>sv01</masv>
        <tensv>Phan Tuan Cuong</tensv>
        <gioitinh>Nam</gioitinh>
        <malop>CNTT10</malop>
        <diem>5</diem>
    </sinhvien>
    <sinhvien>
        <masv>sv02</masv>
        <tensv>Vuong Thu Phuong</tensv>
        <gioitinh>Nu</gioitinh>
        <malop>CNTT10</malop>
        <diem>9</diem>
    </sinhvien>
    <sinhvien>
        <masv>sv03</masv>
        <tensv>Pham Duc Nguyen</tensv>
        <gioitinh>Nam</gioitinh>
        <malop>TCKT10</malop>
        <diem>8</diem>
    </sinhvien>
    <sinhvien>
        <masv>sv04</masv>
        <tensv>Truong Yen Nhi</tensv>
        <gioitinh>Nu</gioitinh>
        <malop>TCKT10</malop>
        <diem>10</diem>
    </sinhvien>
</dssinhvien>
